feat: add script for running benchmarks in batches

diff --git a/tutorials/D4DummySetup/Allrun b/tutorials/D4DummySetup/Allrun
--- a/tutorials/D4DummySetup/Allrun
+++ b/tutorials/D4DummySetup/Allrun
@@ -2,12 +2,32 @@
 # Load OpenFOAM run functions
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
 
-# User settings
-TABLERESOLUTION="51"                # select table resolution (2, 21, 31, 41, 46, 51)
-PARALLEL=true                       # parallel mode?
+CASE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
+
+# User settings, overridable through environment variables
+TABLERESOLUTION="${TABLERESOLUTION:-21}"      # select table resolution (2, 21, 31, 41, 46, 51)
+PARALLEL="${PARALLEL:-false}"                 # parallel mode?
+NPROCS="${NPROCS:-8}"                         # number of MPI ranks when parallel
+TABLE_SUFFIX="${TABLE_SUFFIX:-f}"             # ndtbl precision suffix (f or d)
+TABLE_FILE="${TABLE_FILE:-}"                  # explicit ndtbl file path, if set
+
+if [ -n "$TABLE_FILE" ]; then
+    TABLE_SOURCE="$TABLE_FILE"
+else
+    TABLE_SOURCE="$CASE_DIR/tables/tables_${TABLERESOLUTION}/Tables_${TABLERESOLUTION}_${TABLE_SUFFIX}.ndtbl"
+fi
+
+if [[ "$TABLE_SOURCE" != /* ]]; then
+    TABLE_SOURCE="$CASE_DIR/$TABLE_SOURCE"
+fi
+
+if [ ! -e "$TABLE_SOURCE" ]; then
+    echo "Missing ndtbl input file: $TABLE_SOURCE" >&2
+    exit 1
+fi
 
 # Link grouped ndtbl binary
-ln -sf ../tables/tables_"$TABLERESOLUTION"/Tables.ndtbl ./constant
+ln -sf "$TABLE_SOURCE" "$CASE_DIR/constant/Tables.ndtbl"
 
 # Copy initial conditions
 cp -rf 0_orig 0
@@ -15,12 +35,15 @@ cp -rf 0_orig 0
 # Create Mesh
 runApplication blockMesh
 
-if $PARALLEL; then
+if [ "$PARALLEL" = true ]; then
+    sed -i "s/^numberOfSubdomains[[:space:]].*;/numberOfSubdomains $NPROCS;/" \
+        system/decomposeParDict
+
     # Decompose case
     runApplication decomposePar
 
     # Run solver in parallel
-    runApplication mpirun -np 4 bwRSE4HPCFoam -parallel
+    runApplication mpirun -np "$NPROCS" bwRSE4HPCFoam -parallel
 
     # Reconstruct results
     runApplication reconstructPar
